const categories = {
    "Apartment Building" : 8,
    "Apartment Complex" : 9,
    "Apartment Rental Agency" : 10,
    "Condominium Complex" : 17,
    "Condominium Rental Agency" : 18,
    "Furnished Apartment Building" : 20,
    "Townhouse Complex" : 43,
    "Real Estate Rental Agency" : 59,
    "Real Estate Agency" : 62,
    "Student Dormitory" : 71,
    "Student Housing Center" : 72,
    "Property Management Company" : 74,
    "Housing Development" : 91,
    "Low Income Housing Program" : 92,
    "Real Estate Agents" : 99,
    "RV Park" : 114,
    "Indoor Lodging" : 97,
    "Short Term Apartment Rental Agency" : 73,
    "Historical Landmark" : 124,
    "Office Space Rental Agency" : 80,
    "Executive Suite Rental Agency" : 81,
    "Corporate Office" : 128,
    "Retirement Community" : 33,
    "Business Center" : 121,
    "Outlet Mall" : 126,
    "Shopping Mall" : 127,
    "Automobile Storage Facility" : 13,
    "Boat Storage Facility" : 14,
    "Caravan Storage Facility" : 15,
    "Cold Storage Facility" : 16,
    "Records Storage Facility" : 30,
    "Self-Storage Facility" : 38,
    "Shredding Service" : 41,
    "Storage Facility" : 42,
    "Truck Rental Agency" : 44,
    "Vehicle Storage Facility" : 45,
    "Warehouse" : 48,
    "Wine Storage Facility" : 49,
    "Moving Supply Store" : 28,
    "RV Storage Facility" : 61,
    "Moving and Storage Service" : 64,
    "Packaging Supply Store" : 75,
    "Moving Company" : 76,
    "Self Storage Facility" : 63,
    "Mailbox Rental Service" : 85,
    "Business Management Consultant" : 89,
    "Transportation Service" : 106,
    "Conference Center" : 115,
    "Business to Business Service" : 86,
    "Business Administration Service" : 87,
    "Business Networking Company" : 88,
    "Mailing Service" : 116,
    "Trailer Rental Service" : 117,
    "Fax Service" : 119,
    "Notary Public" : 120,
    "Parking Garage" : 125,
    "Business Park" : 129,
    "Commercial Real Estate Agency" : 123,
    "Adult Day Care Centre" : 2,
    "Adult Foster Care Service" : 3,
    "Aged Care" : 4,
    "Adult Day Care Center" : 1,
    "Aged Care Service" : 5,
    "Assisted Living Facility" : 11,
    "Assisted Living Residence" : 12,
    "Home Care Service" : 21,
    "Home Health Care Service" : 22,
    "Hospice" : 24,
    "Mental Health Service" : 25,
    "Mental Health Services" : 26,
    "Nursing Home" : 29,
    "Rehabilitation Center" : 31,
    "Rehabilitation Centre" : 32,
    "Retirement Village" : 36,
    "Senior Citizens Club" : 40,
    "Senior Citizen Center" : 39,
    "Home Help Service Agency" : 23,
    "Retirement Home" : 35,
    "Nursing Agency" : 60,
    "Diabetes Center" : 118,
    "Real Estate Developer" : 122,
    "Animal Hospital" : 6,
    "Animal Rescue Service" : 7,
    "Emergency Veterinarian Service" : 19,
    "Veterinarian" : 46,
    "Veterinary Care" : 47,
    "Dentist" : 50,
    "Veterinary Pharmacy" : 51,
    "Dog Day Care Center" : 52,
    "Pet Groomer" : 53,
    "Pet Boarding Service" : 54,
    "Pet Adoption Service" : 55,
    "Pet Supply Store" : 56,
    "Dog Trainer" : 57,
    "Kennel" : 58
}